l2loss = read.csv("l2loss.csv")
l1loss = read.csv("l1loss.csv")
FP = read.csv("FP.csv")
FN = read.csv("FN.csv")
RA_1 = read.csv("RA_1.csv")
RA_2 = read.csv("RA_2.csv")

l2loss_pense = read.csv("l2loss_pense.csv")
l1loss_pense = read.csv("l1loss_pense.csv")
FP_pense = read.csv("FP_pense.csv")
FN_pense = read.csv("FN_pense.csv")
RA_1_pense = read.csv("RA_1_pense.csv")
RA_2_pense = read.csv("RA_2_pense.csv")

l2loss_lasso = read.csv("l2loss_lasso.csv")
l1loss_lasso = read.csv("l1loss_lasso.csv")
FP_lasso = read.csv("FP_lasso.csv")
FN_lasso = read.csv("FN_lasso.csv")

mean(l1loss)
quantile(l1loss, probs = c(0.05, 0.95))
mean(l2loss)
quantile(l2loss, probs = c(0.05, 0.95))
mean(FP)
quantile(FP, probs = c(0.05, 0.95))
mean(FN)
quantile(FN, probs = c(0.05, 0.95))
mean(RA_1)
quantile(RA_1, probs = c(0.05, 0.95))
mean(RA_2)
quantile(RA_2, probs = c(0.05, 0.95))

mean(l1loss_lasso)
quantile(l1loss_lasso, probs = c(0.05, 0.95))
mean(l2loss_lasso)
quantile(l2loss_lasso, probs = c(0.05, 0.95))
mean(FP_lasso)
quantile(FP_lasso, probs = c(0.05, 0.95))
mean(FN_lasso)
quantile(FN_lasso, probs = c(0.05, 0.95))

mean(l1loss_pense)
quantile(l1loss_pense, probs = c(0.05, 0.95))
mean(l2loss_pense)
quantile(l2loss_pense, probs = c(0.05, 0.95))
mean(FP_pense)
quantile(FP_pense, probs = c(0.05, 0.95))
mean(FN_pense)
quantile(FN_pense, probs = c(0.05, 0.95))
mean(RA_1_pense)
quantile(RA_1_pense, probs = c(0.05, 0.95))
mean(RA_2_pense)
quantile(RA_2_pense, probs = c(0.05, 0.95))