l2loss = read.csv("l2loss.csv")
l1loss = read.csv("l1loss.csv")
FP = read.csv("FP.csv")
FN = read.csv("FN.csv")
RA_1 = read.csv("RA_1.csv")
RA_2 = read.csv("RA_2.csv")

l2loss_pense = read.csv("l2loss_pense.csv")
l1loss_pense = read.csv("l1loss_pense.csv")
FP_pense = read.csv("FP_pense.csv")
FN_pense = read.csv("FN_pense.csv")
RA_1_pense = read.csv("RA_1_pense.csv")
RA_2_pense = read.csv("RA_2_pense.csv")

l2loss_lasso = read.csv("l2loss_lasso.csv")
l1loss_lasso = read.csv("l1loss_lasso.csv")
FP_lasso = read.csv("FP_lasso.csv")
FN_lasso = read.csv("FN_lasso.csv")

for (i in 1:CASE) {
  mean(l1loss[,i])
  quantile(l1loss[,i], probs = c(0.05, 0.95))
  mean(l2loss[,i])
  quantile(l2loss[,i], probs = c(0.05, 0.95))
  mean(FP[,i])
  quantile(FP[,i], probs = c(0.05, 0.95))
  mean(FN[,i])
  quantile(FN[,i], probs = c(0.05, 0.95))
  mean(RA_1[,i])
  quantile(RA_1[,i], probs = c(0.05, 0.95))
  mean(RA_2[,i])
  quantile(RA_2[,i], probs = c(0.05, 0.95))
  
  mean(l1loss_lasso[,i])
  quantile(l1loss_lasso[,i], probs = c(0.05, 0.95))
  mean(l2loss_lasso[,i])
  quantile(l2loss_lasso[,i], probs = c(0.05, 0.95))
  mean(FP_lasso[,i])
  quantile(FP_lasso[,i], probs = c(0.05, 0.95))
  mean(FN_lasso[,i])
  quantile(FN_lasso[,i], probs = c(0.05, 0.95))
  
  mean(l1loss_pense[,i])
  quantile(l1loss_pense[,i], probs = c(0.05, 0.95))
  mean(l2loss_pense[,i])
  quantile(l2loss_pense[,i], probs = c(0.05, 0.95))
  mean(FP_pense[,i])
  quantile(FP_pense[,i], probs = c(0.05, 0.95))
  mean(FN_pense[,i])
  quantile(FN_pense[,i], probs = c(0.05, 0.95))
  mean(RA_1_pense[,i])
  quantile(RA_1_pense[,i], probs = c(0.05, 0.95))
  mean(RA_2_pense[,i])
  quantile(RA_2_pense[,i], probs = c(0.05, 0.95)) 
}